### ISSUE TITLE
pip install = IOError: [Errno 2] No translation file found for domain: 'dabo'

### ISSUE THREAD

**Issue by CarlFK** [dabodev/dabo#15]
This issue has existed for years.  I think I logged it in previous issue tracker.  it is mentioned in #12 

(test)juser@dhcp244:~$ virtualenv test
New python executable in test/bin/python
Installing setuptools, pip...done.
(test)juser@dhcp244:~$ cd test/
(test)juser@dhcp244:~/test$ . bin/activate
(test)juser@dhcp244:~/test$ pip install git+https://github.com/dabodev/dabo

```
Downloading/unpacking git+https://github.com/dabodev/dabo
  Cloning https://github.com/dabodev/dabo to /tmp/pip-IZECWo-build
  Running setup.py (path:/tmp/pip-IZECWo-build/setup.py) egg_info for package from git+https://github.com/dabodev/dabo

Installing collected packages: Dabo
  Running setup.py install for Dabo

Successfully installed Dabo
Cleaning up...
```

(test)juser@dhcp244:~/test$ python -c "import dabo"

```
2014-11-11 12:05:05 - ERROR - 
No translation file found for domain 'dabo'.
    Locale dir = /usr/lib/locale
    Languages = ['en_US']
    Codeset = UTF-8 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/juser/test/local/lib/python2.7/site-packages/dabo/__init__.py", line 186, in <module>
    dLocalize.install("dabo")
  File "/home/juser/test/local/lib/python2.7/site-packages/dabo/dLocalize.py", line 79, in install
    setLanguage(_defaultLanguage, _defaultEncoding)
  File "/home/juser/test/local/lib/python2.7/site-packages/dabo/dLocalize.py", line 113, in setLanguage
    daboTranslation = gettext.translation("dabo", daboLocaleDir, languages=["en"], codeset=charset)
  File "/usr/lib/python2.7/gettext.py", line 484, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'dabo'
```

For me it is low priority, I have simple enough workaround:

```
cd $(python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")
git clone https://github.com/dabodev/dabo.git dabo-master
ln -s dabo-master/dabo
cd -
```

**Comment by Thumas** [comment]
The locales are not installed by setup.py. A quick fix is copying the locale folder from the source directory to the place where Dabo is installed.
