### ISSUE TITLE
SetBitmap(): only normal menu items can have bitmaps

### ISSUE THREAD

**Issue by emansije** [dabodev/dabo#16]
I'm running Ubuntu 14.10 and got this error when trying to run DaboDemo.py:
```
Traceback (most recent call last):
  File "DaboDemo.py", line 24, in <module>
    main()
  File "DaboDemo.py", line 20, in main
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/dApp.py", line 388, in start
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/dApp.py", line 340, in setup
    self.initUIApp()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/dApp.py", line 380, in initUIApp
    self.uiApp.setup()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/uiApp.py", line 430, in setup
    frm = self.dApp.MainForm = dabo.ui.createForm(mfc)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/__init__.py", line 1356, in createForm
    frm = cls(*args, **kwargs)
  File "/tmp/tmpYWSfJp.py", line 18, in __init__
    super(dForm_14333, self).__init__(parent=parent, attProperties=attProperties, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dForm.py", line 1044, in __init__
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dForm.py", line 40, in __init__
    attProperties=attProperties, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dFormMixin.py", line 76, in __init__
    attProperties=attProperties, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dPemMixin.py", line 202, in __init__
    self._afterInit()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dForm.py", line 58, in _afterInit
    super(BaseForm, self)._afterInit()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dFormMixin.py", line 96, in _afterInit
    self.MenuBar = mbc()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenuBar.py", line 21, in __init__
    pm.dPemMixin.__init__(self, preClass, None, properties, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dPemMixin.py", line 202, in __init__
    self._afterInit()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dBaseMenuBar.py", line 184, in _afterInit
    self.fileMenu = self.appendMenu(FileMenu(self, MenuID="base_file"))
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dBaseMenuBar.py", line 26, in __init__
    super(FileMenu, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenu.py", line 47, in __init__
    attProperties=attProperties, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dPemMixin.py", line 202, in __init__
    self._afterInit()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dBaseMenuBar.py", line 43, in _afterInit
    help=_("Open up a debug output window"))
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenu.py", line 255, in append
    menutype=menutype, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenu.py", line 238, in _createMenuItem
    item = _actualCreation(caption, help, picture, menutype, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenu.py", line 232, in _actualCreation
    _item.Caption = caption
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenuItem.py", line 95, in _setCaption
    self._redefine()
  File "/usr/local/lib/python2.7/dist-packages/Dabo-0.9.14-py2.7.egg/dabo/ui/uiwx/dMenuItem.py", line 72, in _redefine
    self.SetBitmap(self.Icon)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 12546, in SetBitmap
    return _core_.MenuItem_SetBitmap(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/gtk/menu.cpp(724) in SetBitmap(): only normal menu items can have bitmaps
```

**Comment by EdLeafe** [comment]
This has been fixed in the working branch: be446ff8
