### ISSUE TITLE
test_utils.py header and data encoding mismatch 

### ISSUE THREAD

**Issue by CarlFK** [dabodev/dabo#22]
top line is:
```
# -*- coding: utf-8 -*-
```
https://github.com/dabodev/dabo/blob/master/dabo/lib/test/test_utils.py#L1

but the bytes appear to be windows-1250

```
carl@twist:~/temp$ python 
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> b = open('dabo/dabo/lib/test/test_utils.py').read()
>>> s = b.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1183: invalid start byte
>>> s = b.decode('windows-1250')
```
This mismatch is causing 2to3 to error:

  carl@twist:~/temp$ 2to3 dabo/dabo/lib/test/test_utils.py
  UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1183: invalid start byte

changing the top line and no error.

2to3 seems to respect the header.

**Comment by CarlFK** [comment]
I can't figure out how to create a 2nd PR that doesn't eat the first one.   I suspect it will be rejected and the bytes changed to the utf8 encoding but I wasn't really sure how to do that.

**Comment by CarlFK** [comment]
hex versions of the bytes: 
```
        def test_StringFuncs(self):
                teststring = "This is a very long string with Unicode chars: <8e><9a><94>¯ and 1234567890"
                revstring = "0987654321 dna ¯<94><9a><8e> :srahc edocinU htiw gnirts gnol yrev a si sihT"
```
```
        def test_DictFuncs(self):
                testdict = {u"First": 1, u"Second": 2, "Th<94>rd": 3}
```

those are not valid utf-8 - it is valid windows-1250.

to fix either change the top line to windows-1250 or change the bytes to valid utf-8.

**Comment by EdLeafe** [comment]
Closing this as outdated. If there are still issues with the current state of the code, please open a new issue.
