### ISSUE TITLE
invalid literal for int() with base 16: 'nT' in SimpleCrypt

### ISSUE THREAD

**Issue by arnieelkins** [dabodev/dabo#32]
I am trying to make changes to an app I updated last in 2015, which is problem enough.  When I run the source, I get an error:

  File "C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py", line 120, in hexToStr
    for i in range(0, len(aString), 2)]
ValueError: invalid literal for int() with base 16: 'nT'

It is trying to decrypt a password created with the Connection Editor ages ago.  The production code runs, but is packaged in an EXE with py2exe, so I have no idea what versions of the packages were installed. I found a laptop I was using for development back in the day running Win7, and it had Python 2.7.6, which sounds correct, with dabo 0.9.14 that had a SimpleCrypt patch for (I think) a different issue which was crashing the Connection Editor. SimpleCrypt seems to be the same as dabo 0.9.16, which I have tested and it has the same error. The wx versions should all be the same, etc.  I tested with Python 2.7.6, as well as 2.7.16, which is current.

The entire output:

 C:\Users\WBSDev\Downloads\WBS_Tools-master>wbstools.py
win32
C:\Users\WBSDev\Downloads\WBS_Tools-master
('dejavusans', False, False, 'DejaVuSans')
('dejavusans', False, True, 'DejaVuSans-Oblique')
('dejavusans', True, False, 'DejaVuSans-Bold')
('dejavusans', True, True, 'DejaVuSans-BoldOblique')
('dejavusanscondensed', False, False, 'DejaVuSansCondensed')
('dejavusanscondensed', False, True, 'DejaVuSansCondensed-Oblique')
('dejavusanscondensed', True, False, 'DejaVuSansCondensed-Bold')
('dejavusanscondensed', True, True, 'DejaVuSansCondensed-BoldOblique')
('dejavusansextralight', False, False, 'DejaVuSans-ExtraLight')
('dejavusansmono', False, False, 'DejaVuSansMono')
('dejavusansmono', False, True, 'DejaVuSansMono-Oblique')
('dejavusansmono', True, False, 'DejaVuSansMono-Bold')
('dejavusansmono', True, True, 'DejaVuSansMono-BoldOblique')
('dejavuserif', False, False, 'DejaVuSerif')
('dejavuserif', False, True, 'DejaVuSerif-Italic')
('dejavuserif', True, False, 'DejaVuSerif-Bold')
('dejavuserif', True, True, 'DejaVuSerif-BoldItalic')
('dejavuserifcondensed', False, False, 'DejaVuSerifCondensed')
('dejavuserifcondensed', False, True, 'DejaVuSerifCondensed-Italic')
('dejavuserifcondensed', True, False, 'DejaVuSerifCondensed-Bold')
('dejavuserifcondensed', True, True, 'DejaVuSerifCondensed-BoldItalic')
basedir = C:\Windows\Temp
C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py:54: UserWarning: WARNING:
SimpleCrypt is not secure. Please see http://wiki.dabodev.com/SimpleCrypt for mo
re information
  warnings.warn("WARNING: SimpleCrypt is not secure. Please see http://wiki.dabo
dev.com/SimpleCrypt for more information")
Traceback (most recent call last):
  File "C:\Users\WBSDev\Downloads\WBS_Tools-master\WBSTools.py", line 71, in <mo
dule>
    app.dbConnection = app.getConnectionByName(app.dbConnectionName)
  File "C:\Python27\lib\site-packages\dabo\dApp.py", line 1026, in getConnection
ByName
    self.dbConnections[connName] = dabo.db.dConnection(ci)
  File "C:\Python27\lib\site-packages\dabo\db\dConnection.py", line 32, in __ini
t__
    self._connection = self._openConnection(**kwargs)
  File "C:\Python27\lib\site-packages\dabo\db\dConnection.py", line 85, in _open
Connection
    return self._connectInfo.getConnection(forceCreate=self._forceCreate, **kwar
gs)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 79, in getC
onnection
    return self._backendObject.getConnection(self, **kwargs)
  File "C:\Python27\lib\site-packages\dabo\db\dbMySQL.py", line 61, in getConnec
tion
    passwd=connectInfo.revealPW(), port=port)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 111, in rev
ealPW
    return self.decrypt(self.Password)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 105, in dec
rypt
    return self.Application.decrypt(val)
  File "C:\Python27\lib\site-packages\dabo\dApp.py", line 859, in decrypt
    return self.Crypto.decrypt(val)
  File "C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py", line 99, in decr
ypt
    out = self.hexToStr(val)
  File "C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py", line 120, in hex
ToStr
    for i in range(0, len(aString), 2)]
ValueError: invalid literal for int() with base 16: 'nT'

C:\Users\WBSDev\Downloads\WBS_Tools-master>wbstools.py
win32
C:\Users\WBSDev\Downloads\WBS_Tools-master
('dejavusans', False, False, 'DejaVuSans')
('dejavusans', False, True, 'DejaVuSans-Oblique')
('dejavusans', True, False, 'DejaVuSans-Bold')
('dejavusans', True, True, 'DejaVuSans-BoldOblique')
('dejavusanscondensed', False, False, 'DejaVuSansCondensed')
('dejavusanscondensed', False, True, 'DejaVuSansCondensed-Oblique')
('dejavusanscondensed', True, False, 'DejaVuSansCondensed-Bold')
('dejavusanscondensed', True, True, 'DejaVuSansCondensed-BoldOblique')
('dejavusansextralight', False, False, 'DejaVuSans-ExtraLight')
('dejavusansmono', False, False, 'DejaVuSansMono')
('dejavusansmono', False, True, 'DejaVuSansMono-Oblique')
('dejavusansmono', True, False, 'DejaVuSansMono-Bold')
('dejavusansmono', True, True, 'DejaVuSansMono-BoldOblique')
('dejavuserif', False, False, 'DejaVuSerif')
('dejavuserif', False, True, 'DejaVuSerif-Italic')
('dejavuserif', True, False, 'DejaVuSerif-Bold')
('dejavuserif', True, True, 'DejaVuSerif-BoldItalic')
('dejavuserifcondensed', False, False, 'DejaVuSerifCondensed')
('dejavuserifcondensed', False, True, 'DejaVuSerifCondensed-Italic')
('dejavuserifcondensed', True, False, 'DejaVuSerifCondensed-Bold')
('dejavuserifcondensed', True, True, 'DejaVuSerifCondensed-BoldItalic')
basedir = C:\Windows\Temp
C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py:54: UserWarning: WARNING: SimpleCrypt is not secure. Please see ht
tp://wiki.dabodev.com/SimpleCrypt for more information
  warnings.warn("WARNING: SimpleCrypt is not secure. Please see http://wiki.dabodev.com/SimpleCrypt for more information
")
Traceback (most recent call last):
  File "C:\Users\WBSDev\Downloads\WBS_Tools-master\WBSTools.py", line 71, in <module>
    app.dbConnection = app.getConnectionByName(app.dbConnectionName)
  File "C:\Python27\lib\site-packages\dabo\dApp.py", line 1026, in getConnectionByName
    self.dbConnections[connName] = dabo.db.dConnection(ci)
  File "C:\Python27\lib\site-packages\dabo\db\dConnection.py", line 32, in __init__
    self._connection = self._openConnection(**kwargs)
  File "C:\Python27\lib\site-packages\dabo\db\dConnection.py", line 85, in _openConnection
    return self._connectInfo.getConnection(forceCreate=self._forceCreate, **kwargs)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 79, in getConnection
    return self._backendObject.getConnection(self, **kwargs)
  File "C:\Python27\lib\site-packages\dabo\db\dbMySQL.py", line 61, in getConnection
    passwd=connectInfo.revealPW(), port=port)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 111, in revealPW
    return self.decrypt(self.Password)
  File "C:\Python27\lib\site-packages\dabo\db\dConnectInfo.py", line 105, in decrypt
    return self.Application.decrypt(val)
  File "C:\Python27\lib\site-packages\dabo\dApp.py", line 859, in decrypt
    return self.Crypto.decrypt(val)
  File "C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py", line 99, in decrypt
    out = self.hexToStr(val)
  File "C:\Python27\lib\site-packages\dabo\lib\SimpleCrypt.py", line 120, in hexToStr
    for i in range(0, len(aString), 2)]
ValueError: invalid literal for int() with base 16: 'nT'

Any ideas how to fix this? I used uncompyle6 to recreate the SimpleCrypt file from the compiled version in the EXE, and it appears to be identical, which would seem to indicate a different source of the problem.  I do not know enough about the internals of all the tools in the toolchain to know where to even look for the solution.

The production code runs against only the files in the EXE, so if there is a way to compare those to the current environment on the machine, I would be happy to do so.  The EXE keeps only .pyc or .pyo files, and the directory structure is mangled by py2exe.  I have no idea how the code works when running from the EXE,  Help!
[SimpleCrypt.txt](https://github.com/dabodev/dabo/files/3366648/SimpleCrypt.txt)

 

>

**Comment by jfabiani** [comment]
What version of wxPython (but unlikely the problem)?  It sounds like you 
have updated some module (maybe without realizing it?).  Also try 
removing the font as it is a unicode type with added bytes (at least out 
of the connection file).  The connection file is not expecting unicode. 
Is there a reason you can't just rerun "CxnEditor.py" (connection 
editor) and recreate the connection string?  And you can test the 
connection while in the editor.

Have you also lost the password to the database? and that is what you 
are trying to recover?

Johnf

**Comment by EdLeafe** [comment]
On Jul 7, 2019, at 11:15 PM, arnieelkins <notifications@github.com> wrote:
> 
> ValueError: invalid literal for int() with base 16: ‘nT'

Apparently something corrupted the file, so that the stored password is not being read correctly. SimpleCrypt encrypts by generating a hex version of the original string, and then interspersing random characters within the hex characters. Decryption reverses the process by removing the non-hex characters and then converting what’s left from hex.

> Any ideas how to fix this? I used uncompyle6 to recreate the SimpleCrypt file from the compiled version in the EXE, and it appears to be identical, which would seem to indicate a different source of the problem. I do not know enough about the internals of all the tools in the toolchain to know where to even look for the solution.

Since you said this was a connection password, it would have been stored in a .cxn file. I’m not sure if your decompile tools can return individual files, but if it can, we can see if there’s a way to extract the correct password. Assuming that we can do that, would you have any way to recompile the EXE? In other words, do you have the source code for the app?


-- Ed Leafe

**Comment by EdLeafe** [comment]
Closing this with efcefdf, which removes SimpleCrypt. If you still have issues, please create a new issue.
